from tkinter import *
from PIL import Image,ImageTk
import cv2
import pridiction as n
windows=Tk()
def readimage():
    s=Entry1.get()
    ip='X:/kbproject/frontend/testimages/'+s
    image = Image.open(ip)
    image.thumbnail((200,200), Image.ANTIALIAS)
    can47.image=ImageTk.PhotoImage(image)
    can47.create_image(0,0,image=can47.image,anchor=NW)
    
def writeresult():
    s=Entry1.get()
    a='testimages/'+s
    n.recfunc(a)
    ip='X:/kbproject/frontend/output.jpg'
    image = Image.open(ip)
    image.thumbnail((200,200), Image.ANTIALIAS)
    Canvas2.image=ImageTk.PhotoImage(image)
    Canvas2.create_image(0,0,image=Canvas2.image,anchor=NW)

def bigimageresult():
    image = cv2.imread('output.jpg')
    cv2.imshow('OUTPUT IMAGE',image)
    cv2.waitKey()
    cv2.destroyAllWindows()

def bigimageinput():
    s=Entry1.get()
    a='testimages/'+s
    image = cv2.imread(a)
    cv2.imshow('INPUT IMAGE',image)
    cv2.waitKey()
    cv2.destroyAllWindows()

windows.geometry("600x517+428+70")
windows.title("FGD G24")
windows.configure(background="#d9d9d9")
        
Label1 = Label(windows)
Label1.place(relx=0.16, rely=0.02, height=21, width=420)
Label1.configure(background="#d9d9d9")
Label1.configure(disabledforeground="#a3a3a3")
Label1.configure(font="-family {Arial Black} -size 13 -weight bold -slant roman -underline 1 -overstrike 0")
Label1.configure(foreground="#000000")
Label1.configure(text='''FACE DETECTION & GENDER PRIDICTION''')
Label1.configure(width=420)

Label2 = Label(windows)
Label2.place(relx=0.15, rely=0.08, height=31, width=114)
Label2.configure(background="#d9d9d9")
Label2.configure(disabledforeground="#a3a3a3")
Label2.configure(font="-family {Segoe UI Black} -size 10 -weight bold -slant roman -underline 1 -overstrike 0")
Label2.configure(foreground="#000000")
Label2.configure(text='''INPUT IMAGE''')
Label2.configure(width=114)

Entry1 = Entry(windows)
Entry1.place(relx=0.37, rely=0.08,height=30, relwidth=0.31)
Entry1.configure(background="white")
Entry1.configure(disabledforeground="#a3a3a3")
Entry1.configure(font='Arial')
Entry1.configure(foreground="#000000")
Entry1.configure(insertbackground="black")
Entry1.configure(width=184)

Button1 = Button(windows,command=readimage)
Button1.place(relx=0.7, rely=0.08, height=34, width=67)
Button1.configure(activebackground="#d9d9d9")
Button1.configure(activeforeground="#000000")
Button1.configure(background="#d9d9d9")
Button1.configure(borderwidth="5")
Button1.configure(disabledforeground="#a3a3a3")
Button1.configure(font="-family {Segoe UI Black} -size 10 -weight bold -slant roman -underline 0 -overstrike 0")
Button1.configure(foreground="#000000")
Button1.configure(highlightbackground="#d9d9d9")
Button1.configure(highlightcolor="black")
Button1.configure(pady="0")
Button1.configure(text='''Upload''')
Button1.configure(width=67)

can47 = Canvas(windows)
can47.place(relx=0.12, rely=0.17, relheight=0.24, relwidth=0.29)
can47.configure(background="#d9d9d9")
can47.configure(borderwidth="2")
can47.configure(highlightbackground="#f0f0f0")
can47.configure(insertbackground="black")
can47.configure(relief=RIDGE)
can47.configure(selectbackground="#c4c4c4")
can47.configure(selectforeground="black")
can47.configure(width=175)

Button2 = Button(windows,command=bigimageinput)
Button2.place(relx=0.53, rely=0.25, height=34, width=119)
Button2.configure(activebackground="#d9d9d9")
Button2.configure(activeforeground="#000000")
Button2.configure(background="#d9d9d9")
Button2.configure(borderwidth="5")
Button2.configure(disabledforeground="#a3a3a3")
Button2.configure(font="-family {Segoe UI Black} -size 10 -weight bold -slant roman -underline 0 -overstrike 0")
Button2.configure(foreground="#000000")
Button2.configure(highlightbackground="#d9d9d9")
Button2.configure(highlightcolor="black")
Button2.configure(pady="0")
Button2.configure(text='''View Full Image''')

Label3 = Label(windows)
Label3.place(relx=0.15, rely=0.54, height=31, width=114)
Label3.configure(background="#d9d9d9")
Label3.configure(disabledforeground="#a3a3a3")
Label3.configure(font="-family {Segoe UI Black} -size 10 -weight bold -slant roman -underline 1 -overstrike 0")
Label3.configure(foreground="#000000")
Label3.configure(text='''OUTPUT IMAGE''')
Label3.configure(width=104)

Canvas2 = Canvas(windows)
Canvas2.place(relx=0.12, rely=0.63, relheight=0.24, relwidth=0.29)

Canvas2.configure(background="#d9d9d9")
Canvas2.configure(borderwidth="2")
Canvas2.configure(insertbackground="black")
Canvas2.configure(relief=RIDGE)
Canvas2.configure(selectbackground="#c4c4c4")
Canvas2.configure(selectforeground="black")
Canvas2.configure(width=178)

Button3 = Button(windows,command=bigimageresult)
Button3.place(relx=0.53, rely=0.74, height=34, width=119)
Button3.configure(activebackground="#d9d9d9")
Button3.configure(activeforeground="#000000")
Button3.configure(background="#d9d9d9")
Button3.configure(borderwidth="5")
Button3.configure(disabledforeground="#a3a3a3")
Button3.configure(font="-family {Segoe UI Black} -size 10 -weight bold -slant roman -underline 0 -overstrike 0")
Button3.configure(foreground="#000000")
Button3.configure(highlightbackground="#d9d9d9")
Button3.configure(highlightcolor="black")
Button3.configure(pady="0")
Button3.configure(text='''View Full Image''')

Button4 = Button(windows,command=writeresult)
Button4.place(relx=0.38, rely=0.46, height=34, width=167)
Button4.configure(activebackground="#d9d9d9")
Button4.configure(activeforeground="#000000")
Button4.configure(background="GREEN")
Button4.configure(borderwidth="5")
Button4.configure(disabledforeground="#a3a3a3")
Button4.configure(font="-family {Segoe UI Black} -size 11 -weight bold -slant italic -underline 0 -overstrike 0")
Button4.configure(foreground="#000000")
Button4.configure(highlightbackground="LIGHT GREEN")
Button4.configure(highlightcolor="black")
Button4.configure(pady="0")
Button4.configure(text='''START PROGRAM''')
Button4.configure(width=167)


Button6 = Button(windows,command=windows.destroy)
Button6.place(relx=0.88, rely=0.93, height=34, width=57)
Button6.configure(activebackground="#d9d9d9")
Button6.configure(activeforeground="#000000")
Button6.configure(background="RED")
Button6.configure(borderwidth="5")
Button6.configure(disabledforeground="#a3a3a3")
Button6.configure(font="-family {Segoe UI Black} -size 10 -weight bold -slant roman -underline 0 -overstrike 0")
Button6.configure(foreground="#000000")
Button6.configure(highlightbackground="#d9d9d9")
Button6.configure(highlightcolor="black")
Button6.configure(pady="0")
Button6.configure(text='''Exit''')

windows.mainloop()
